# 3.13.1 Exercise 1: functions

In [21]:
def calc(a, b, oper = 'sum'):
    if oper == 'multiply':
        return a * b
    if oper == 'sum':
        return a + b
    else:
        return 'Error'

In [42]:
calc(4, 5, 'multiply')

20

In [43]:
calc(3, 5)

8

In [44]:
calc(1,2, 'something')

'Error'

# 3.13.2 Exercise 2: functions + list + loop

In [46]:
x = [1, 2, 2, 3, 3, 2, 2]

- adjacent duplicate

In [47]:
def remove_adjacent_duplicate(x):
    idx = 0
    while idx < len(x)-1:
        if x[idx] == x[idx+1]:
            del x[idx]
        else:
            idx += 1
    return x

In [48]:
remove_adjacent_duplicate(x)

[1, 2, 3, 2]

- duplicate

In [49]:
def remove_duplicate(x):
    return list(set(x))

In [50]:
remove_duplicate(x)

[1, 2, 3]

# Duchesnay(2019)Statistics and Machine Learning in Python
2020/03/21

Original: reference.ipynb; https://github.com/justmarkham/python-reference

## Table of contents

1. <a href="#1.-Create-arrays">Create arrays</a>
2. <a href="#2.-Examining-arrays">Examining arrays</a>
3. <a href="#3.-Reshaping">Reshaping</a>
4. <a href="#4.-Stack-arrays">Stack arrays</a>
5. <a href="#5.-Selection">Selection</a>
6. <a href="#6.-Vectorized-operations">Vectorized operations</a>
7. <a href="#7.-Brodcasting">Brodcasting</a>
8. <a href="#8.-Exercises">Exercises</a>

## 1. Create arrays

In [51]:
import numpy as np
from pprint import pprint #print가 좀더 예쁘게 나오게 해줌

In [12]:
data1 = [1, 2, 3, 4, 5] # list
arr1 = np.array(data1) # 1d array
data2 = [range(1, 5), range(5, 9)] # list of lists
arr2 = np.array(data2) # 2d array
arr2.tolist() # convert array back to list

pprint(arr1)
pprint(arr2)
pprint(arr2.tolist())

array([1, 2, 3, 4, 5])
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [52]:
pprint(np.zeros(10))
pprint(np.zeros((3, 6)))
pprint(np.ones(10))
pprint(np.ones((3, 6)))
pprint(np.linspace(0, 1, 5)) # 0 to 1 (inclusive) with 5 points
pprint(np.logspace(0, 3, 4)) # 10^0 to 10^3 (inclusive) with 4 points
pprint(np.log(np.logspace(0, 3, 4)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])
array([0.  , 0.25, 0.5 , 0.75, 1.  ])
array([   1.,   10.,  100., 1000.])
array([0.        , 2.30258509, 4.60517019, 6.90775528])


In [60]:
int_array = np.arange(5)
float_array = int_array.astype(float)

pprint(int_array)
pprint(float_array)

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4.])


[<a href="#Table-of-contents">Back to top</a>]

## 2. Examining arrays

In [61]:
pprint(float_array.dtype) # float64
pprint(arr2.dtype) # int32
pprint(arr2.ndim) # 2
pprint(arr2.shape) # (2, 4) - axis 0 is rows, axis 1 is columns
pprint(arr2.size) # 8 - total number of elements
pprint(len(arr2)) # 2 - size of first dimension (aka axis)

dtype('float64')
dtype('int32')
2
(2, 4)
8
2


[<a href="#Table-of-contents">Back to top</a>]

## 3. Reshaping

In [62]:
arr = np.arange(10, dtype=float).reshape((2, 5))
pprint(arr.shape)
pprint(arr)
pprint(arr.reshape(5, 2))

(2, 5)
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])
array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])


In [63]:
a = np.array([0, 1])
a_col = a[:, np.newaxis]
pprint(a)
pprint(a_col)
#or
a_col = a[:, None]
pprint(a_col)

array([0, 1])
array([[0],
       [1]])
array([[0],
       [1]])


In [147]:
pprint(a_col.T) #Transpose

array([[0, 1]])


In [148]:
arr_flt = arr.flatten()
arr_flt[0] = 33
pprint(arr_flt)
pprint(arr)

array([33.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])


In [149]:
arr_flt = arr.ravel()
arr_flt[0] = 33
pprint(arr_flt)
pprint(arr) # flatten과의 차이, 원래 객체의 데이터도 값이 변한다

array([33.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
array([[33.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])


[<a href="#Table-of-contents">Back to top</a>]

## 4. Stack arrays

In [69]:
a = np.array([0, 1])
b = np.array([2, 3])
ab = np.stack((a, b)).T
pprint(ab)
# or
pprint(np.hstack((a[:, None], b[:, None])))
# or
pprint(np.hstack((a[:, np.newaxis], b[:, np.newaxis])))
# or
pprint(np.vstack((a, b)).T)

array([[0, 2],
       [1, 3]])
array([[0, 2],
       [1, 3]])
array([[0, 2],
       [1, 3]])
array([[0, 2],
       [1, 3]])


In [70]:
np.hstack((a, b))

array([0, 1, 2, 3])

In [71]:
np.vstack((a, b))

array([[0, 1],
       [2, 3]])

[<a href="#Table-of-contents">Back to top</a>]

## 5. Selection

In [81]:
arr = np.arange(10, dtype=float).reshape((2, 5))

pprint(arr)
pprint(arr[0])
pprint(arr[0, 3])
pprint(arr[0][3])

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])
array([0., 1., 2., 3., 4.])
3.0
3.0


In [82]:
pprint(arr[0, :])
pprint(arr[:, 0])
pprint(arr[:, :2])
pprint(arr[:, 2:])

arr2 = arr[:, 1:4]
pprint(arr2)

array([0., 1., 2., 3., 4.])
array([0., 5.])
array([[0., 1.],
       [5., 6.]])
array([[2., 3., 4.],
       [7., 8., 9.]])
array([[1., 2., 3.],
       [6., 7., 8.]])


In [83]:
arr2[0, 0] = 33
pprint(arr2)
pprint(arr) # Slicing returns a view (not a copy)

array([[33.,  2.,  3.],
       [ 6.,  7.,  8.]])
array([[ 0., 33.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])


In [86]:
pprint(arr[0, :5:2])
pprint(arr[0, 2::-1])
pprint(arr[0, 2:0:-1])
pprint(arr[0, ::-2])
pprint(arr[0, ::-1])

array([0., 2., 4.])
array([ 2., 33.,  0.])
array([ 2., 33.])
array([4., 2., 0.])
array([ 4.,  3.,  2., 33.,  0.])


In [155]:
arr2 = arr[:, [1,2,3]] # return a copy
pprint(arr2)
arr2[0, 0] = 44
pprint(arr2)
pprint(arr) # 값이 바뀌지 않음

array([[33.,  2.,  3.],
       [ 6.,  7.,  8.]])
array([[44.,  2.,  3.],
       [ 6.,  7.,  8.]])
array([[ 0., 33.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])


In [156]:
arr2 = arr[arr > 5] # return a copy, 1행부터 차례대로 5보다 큰값만 뽑아서 array로 나열 후 copy
pprint(arr2)
arr2[0] = 44
pprint(arr2)
pprint(arr)

array([33.,  6.,  7.,  8.,  9.])
array([44.,  6.,  7.,  8.,  9.])
array([[ 0., 33.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])


In [157]:
arr[arr > 5] = 0
pprint(arr)

array([[0., 0., 2., 3., 4.],
       [5., 0., 0., 0., 0.]])


In [87]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
pprint(names == 'Bob') # returns a boolean array
pprint(names[names != 'Bob']) # logical selection
pprint((names == 'Bob') | (names == 'Will')) # keywords "and/or" don't work with boolean arrays
pprint((names == 'Bob') & (names != 'Will'))
names[names != 'Bob'] = 'Joe' # assign based on a logical selection
pprint(np.unique(names))# set function(집합으로 unique value만 array로)
pprint(names)

array([ True, False, False,  True])
array(['Joe', 'Will'], dtype='<U4')
array([ True, False,  True,  True])
array([ True, False, False,  True])
array(['Bob', 'Joe'], dtype='<U4')
array(['Bob', 'Joe', 'Joe', 'Bob'], dtype='<U4')


[<a href="#Table-of-contents">Back to top</a>]

## 6. Vectorized operations

In [159]:
nums = np.arange(5)
pprint(nums)
pprint(nums * 10) # multiply each element by 10
nums = np.sqrt(nums) # square root of each element
pprint(nums)
pprint(np.ceil(nums)) # also floor(버림), rint(반올림) (round to nearest int), 올림
pprint(np.isnan(nums)) # checks for NaN
pprint(nums + np.arange(5)) # add element-wise
pprint(np.maximum(nums, np.array([1, -2, 3, -4, 5]))) # compare element-wise, 원소끼리 비교해서 maximum값 반환

array([0, 1, 2, 3, 4])
array([ 0, 10, 20, 30, 40])
array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])
array([0., 1., 2., 2., 2.])
array([False, False, False, False, False])
array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ])
array([1.        , 1.        , 3.        , 1.73205081, 5.        ])


In [160]:
# Compute Euclidean distance between 2 vectors
vec1 = np.random.randn(10) # standard normal distribution에서 10개의 샘플을 가져옴
vec2 = np.random.randn(10)
pprint(vec1)
pprint(vec2)
dist = np.sqrt(np.sum((vec1 - vec2) ** 2))
pprint(dist)

array([-2.79962074e-01,  1.31281104e+00, -9.27155784e-01, -4.01302169e-01,
       -2.31085929e+00, -2.08460156e+00,  4.59241643e-01,  1.62191344e+00,
        1.94515120e-01, -2.08631547e-03])
array([ 0.67087863, -0.22222597, -1.05032969, -1.53994168, -0.18768735,
        1.3381685 ,  0.33054907,  0.65390323,  0.0722828 , -0.17813191])
4.668496623021033


In [106]:
# math and stats
rnd = np.random.randn(4, 2) # random normals in 4x2 array
pprint(rnd)
pprint(rnd.mean())
pprint(rnd.std())
pprint(rnd.argmin()) # index of minimum element, 행렬형태에서는 위에부터, 왼쪽에서 오르쪽으로 0, 1, 2.....
pprint(rnd.sum())
pprint(rnd.sum(axis=0)) # sum of columns
pprint(rnd.sum(axis=1)) # sum of rows

array([[-0.98284437, -0.04131148],
       [ 0.80107667,  1.34960946],
       [-0.34403479,  0.28966606],
       [ 2.08390068,  0.76218799]])
0.48978127789368686
0.9108795587913807
0
3.918250223149495
array([1.5580982 , 2.36015203])
array([-1.02415585,  2.15068613, -0.05436873,  2.84608867])


In [90]:
rnd = rnd.flatten()
pprint(rnd)
pprint(rnd.mean())
pprint(rnd.std())
pprint(rnd.argmin()) # index of minimum element
pprint(rnd.sum())

array([-0.28504399, -0.75980108,  1.34836928, -0.97766119,  0.99750446,
       -0.00429155, -1.28836087, -0.76445081])
-0.21671696913615818
0.8871324060053231
6
-1.7337357530892654


In [92]:
# methods for boolean arrays
pprint((rnd > 0).sum()) # counts number of positive values
pprint((rnd > 0).any()) # checks if any value is True
pprint((rnd > 0).all()) # checks if all values are True

3
True
False


In [107]:
# random numbers
np.random.seed(12234) # Set the seed
pprint(np.random.rand(2, 3)) # 2 x 3 matrix in [0, 1]
pprint(np.random.randn(10)) # random normals (mean 0, sd 1)
pprint(np.random.randint(0, 2, 10)) # 10 randomly picked 0 or 1

array([[0.00630595, 0.20303476, 0.76478993],
       [0.55513384, 0.74358546, 0.93777808]])
array([-2.79962074e-01,  1.31281104e+00, -9.27155784e-01, -4.01302169e-01,
       -2.31085929e+00, -2.08460156e+00,  4.59241643e-01,  1.62191344e+00,
        1.94515120e-01, -2.08631547e-03])
array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])


In [109]:
# np.random.seed(12234)
np.random.rand(2,3)

array([[0.00630595, 0.20303476, 0.76478993],
       [0.55513384, 0.74358546, 0.93777808]])

[<a href="#Table-of-contents">Back to top</a>]

## 7. Brodcasting

In [166]:
a = np.array([[ 0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]]) # 4 x 3
b = np.array([0, 1, 2]) # 1 x 3
pprint(a + b) # 4 x 3

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])


In [167]:
a = np.array([[[ 0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]],
             [[ 0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]]]) # 2 x 4 x 3
b = np.array([[0, 1, 2], [0, 1, 2], [3, 4, 5], [3, 4, 5]]) # 1 x 4 x 3
pprint(a + b) # 2 x 4 x 3

array([[[ 0,  1,  2],
        [10, 11, 12],
        [23, 24, 25],
        [33, 34, 35]],

       [[ 0,  1,  2],
        [10, 11, 12],
        [23, 24, 25],
        [33, 34, 35]]])


[<a href="#Table-of-contents">Back to top</a>]

## 8. Exercises

In [116]:
X = np.random.randn(4, 2) # random normals in 4x2 array

- For each column find the row index of the minimum value

In [117]:
X

array([[ 0.33054907,  0.65390323],
       [ 0.0722828 , -0.17813191],
       [-0.22806409, -0.40984287],
       [-1.11223407,  1.38240838]])

In [118]:
X.argmin(axis=0)

array([3, 2], dtype=int64)

- Write a function standardize(X) that return an array whose columns are centered and scaled (by std-dev).

In [119]:
def standardize(X):
    standardize_x = (X - X.mean(axis=0)) / X.std(axis=0)
    return standardize_x

In [120]:
standardize(X)

array([[ 1.03839937,  0.41126522],
       [ 0.56366737, -0.76133523],
       [ 0.01158491, -1.0878892 ],
       [-1.61365165,  1.43795921]])

In [121]:
standardize(X).mean(axis=0)

array([0., 0.])

In [122]:
standardize(X).std(axis=0)

array([1., 1.])

[<a href="#Table-of-contents">Back to top</a>]